# Generated by Django 3.1.4 on 2020-12-28 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_phonenumber',
            new_name='phonenumber',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='foodcartapp.product', verbose_name='Товар'),
        ),
    ]
