# Generated by Django 3.1.4 on 2021-01-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='choices',
            new_name='payment_type',
        ),
    ]
